#
# RuboCop configuration
#

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "test/fixtures/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "app/views/**/*"
    - "config/environments/*"
    - "node_modules/**/*"

# Layout Cops

Layout/LineLength:
  Description: "Limit lines to 140 characters."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#80-character-limits"
  Max: 140

# Metrics Cops

Metrics/ClassLength:
  Description: "Avoid classes longer than 100 lines of code."
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Description: "Avoid modules longer than 100 lines of code."
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: "Pass no more than four parameters into a method."
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: "Avoid methods longer than 20 lines of code."
  StyleGuide: "<https://github.com/bbatsov/ruby-style-guide#short-methods>"
  Max: 20
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  CountAsOne: ["array", "hash", and "heredoc"]
  Max: 25
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group

# Style Cops

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#consistent-string-literals"
  EnforcedStyle: double_quotes
  Enabled: true

Style/SymbolArray:
  EnforcedStyle: brackets

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/SignalException:
  EnforcedStyle: only_raise

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

# Rails Cops

Rails/Delegate:
  Description: "Prefer delegate method for delegations."
  Enabled: false

# Bundler Cops

Bundler/OrderedGems:
  Enabled: false
